/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Utilitarios.Conexao;
import Utilitarios.Tabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Augusto
 */
public class FrmFuncionario extends javax.swing.JFrame {

    Conexao conexao = new Conexao();
    public FrmFuncionario() {
        initComponents();
        conexao.Conectar();
        preencherCpf();
        preencherData();
        preencherTabela("SELECT * FROM funcionario ORDER BY cod_funcionario");
        //conexao.executaSQL("SELECT * FROM funcionario ORDER BY sexo");
        //txtComboSexo.removeAllItems();
       // try{
           // conexao.rs.first();
            //do{
             //   txtComboSexo.addItem(conexao.rs.getString("sexo"));
           // }while (conexao.rs.next());
            
       // } catch (SQLException ex){
         //   JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combobox! \n ERRO: " + ex);
       // }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtFuncao = new javax.swing.JTextField();
        txtComboSexo = new javax.swing.JComboBox<>();
        btAdicionar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTabela = new javax.swing.JTable();
        btPrimeiro = new javax.swing.JButton();
        btUltimo = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtComboEstado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtComboStatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionarios");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 454));

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Função:");

        jLabel5.setText("sexo:");

        txtCodigo.setEnabled(false);

        txtNome.setEnabled(false);

        txtFuncao.setEnabled(false);

        txtComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        btAdicionar.setText("Adicionar");
        btAdicionar.setToolTipText("utilize para adicionar um novo funcionario");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("utilize para salvar um novo funcionario");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.setToolTipText("utilize para alterar algum funcionario");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("utilize atravez do codigo do funcionario");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("utilize para cancelar a operação");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        txtTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txtTabela);

        btPrimeiro.setText("Primeiro");
        btPrimeiro.setToolTipText("mostra o primeiro dado cadastrado");
        btPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrimeiroActionPerformed(evt);
            }
        });

        btUltimo.setText("Ultimo");
        btUltimo.setToolTipText("mostra o ultimo dado cadastrado");
        btUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimoActionPerformed(evt);
            }
        });

        btAnterior.setText("Anterior");
        btAnterior.setToolTipText("mostra o dado anterior");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btProximo.setText("Proximo");
        btProximo.setToolTipText("mostra o proximo dado");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        btVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_voltar.png"))); // NOI18N
        btVoltar.setToolTipText("clique para voltar para a janela anterior");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        jLabel6.setText("CPF:");

        txtCPF.setEnabled(false);

        jLabel7.setText("Data de Adimissão:");

        txtData.setEnabled(false);

        jLabel8.setText("Endereço:");

        txtEndereco.setEnabled(false);

        jLabel9.setText("Cidade:");

        txtCidade.setEnabled(false);
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        txtComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA\t", "CE", "DF", "ES\t", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        txtComboEstado.setSelectedIndex(12);
        txtComboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComboEstadoActionPerformed(evt);
            }
        });

        jLabel10.setText("Estado:");

        txtComboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        jLabel11.setText("Status:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFuncao))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUltimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProximo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btSalvar)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir)
                    .addComponent(btCancelar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPrimeiro)
                    .addComponent(btUltimo)
                    .addComponent(btAnterior)
                    .addComponent(btProximo))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Formulario de cadastro de funcionarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(616, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
    txtNome.setText("");
    txtCodigo.setText("");
    txtFuncao.setText("");
    txtCPF.setText("");
    txtData.setText("");
    txtEndereco.setText("");
    txtCidade.setText("");
    txtNome.setEnabled(false);
    txtCodigo.setEnabled(false);
    txtFuncao.setEnabled(false);
    txtCPF.setEnabled(false);
    txtData.setEnabled(false);
    txtEndereco.setEnabled(false);
    txtCidade.setEnabled(false);
    btAdicionar.setEnabled(true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimoActionPerformed
    txtNome.setEnabled(true);
    txtFuncao.setEnabled(true);
    txtCPF.setEnabled(true);
    txtData.setEnabled(true);
    txtEndereco.setEnabled(true);
    txtCidade.setEnabled(true);
    
        try {
            conexao.executaSQL("SELECT * FROM funcionario");
            conexao.rs.last();
            txtCodigo.setText(conexao.rs.getString("cod_funcionario"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtFuncao.setText(conexao.rs.getString("funcao"));
            txtComboSexo.setSelectedItem(conexao.rs.getString("sexo"));
            txtCPF.setText(conexao.rs.getString("cpf"));
            txtData.setText(conexao.rs.getString("data_adimissao"));
            txtEndereco.setText(conexao.rs.getString("endereco"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
            txtComboStatus.setSelectedItem(conexao.rs.getString("status"));
            btUltimo.setEnabled(false);
            btProximo.setEnabled(false);
            btPrimeiro.setEnabled(true);
            btAnterior.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao exibir dados!\nERRO: " + ex);
        }
    }//GEN-LAST:event_btUltimoActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
    txtNome.setText("");
    txtCodigo.setText("");
    txtFuncao.setText("");
    txtCPF.setText("");
    txtData.setText("");
    txtEndereco.setText("");
    txtCidade.setText("");
    txtNome.setEnabled(true);
    txtCodigo.setEnabled(false);
    txtFuncao.setEnabled(true);
    txtCPF.setEnabled(true);
    txtData.setEnabled(true);
    txtEndereco.setEnabled(true);
    txtCidade.setEnabled(true);
    btExcluir.setEnabled(false);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
    try {
       
            PreparedStatement pst = conexao.conn.prepareStatement("INSERT INTO funcionario (nome, funcao, sexo, cpf, data_adimissao, endereco, cidade, estado, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ? )");
            
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtFuncao.getText());
            pst.setString(3, txtComboSexo.getSelectedItem().toString());
            pst.setString(4, txtCPF.getText());
            pst.setString(5, txtData.getText());
            pst.setString(6, txtEndereco.getText());
            pst.setString(7, txtCidade.getText());
            pst.setString(8, txtComboEstado.getSelectedItem().toString());
            pst.setString(9, txtComboStatus.getSelectedItem().toString());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Funcionario inserido com sucesso!");
            preencherTabela("SELECT * FROM funcionario ORDER BY cod_funcionario");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro na inserção! \n ERRO: " + ex);
        }
        btExcluir.setEnabled(true);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
    try{
            
            PreparedStatement pst = conexao.conn.prepareStatement("UPDATE funcionario SET nome = ?, funcao = ?, sexo = ?, cpf = ?, data_adimissao = ?, endereco = ?, cidade = ?, estado = ?, status = ?  WHERE cod_funcionario = ?");
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtFuncao.getText());
            pst.setString(3, txtComboSexo.getSelectedItem().toString());
            pst.setString(4, txtCPF.getText());
            pst.setString(5, txtData.getText());
            pst.setString(6, txtEndereco.getText());
            pst.setString(7, txtCidade.getText());
            pst.setString(8, txtComboEstado.getSelectedItem().toString());
            pst.setString(9, txtComboStatus.getSelectedItem().toString());
            pst.setInt(10, Integer.parseInt(txtCodigo.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"funcionario alterado com sucesso!");
            preencherTabela("SELECT * FROM funcionario ORDER BY cod_funcionario");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro na alteração! \n ERRO: " + ex);
            
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
    if(txtCodigo.isEnabled() == false){
    
    txtCodigo.setEnabled(true);
} else{ 
    if(txtCodigo.getText().equalsIgnoreCase("") == false){
        try{
            
            PreparedStatement pst = conexao.conn.prepareStatement("DELETE FROM funcionario WHERE cod_funcionario = ?");
            pst.setString(1, txtCodigo.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Funcionario excluido com sucesso!");
            preencherTabela("SELECT * FROM funcionario ORDER BY cod_funcionario");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro na exclusão! \n ERRO: " + ex);
            
        }
        txtCodigo.setText("");
        txtCodigo.setEnabled(false);
        
} else { txtCodigo.setEnabled(false);
    }
    }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrimeiroActionPerformed
    txtNome.setEnabled(true);
    txtFuncao.setEnabled(true);
    txtCPF.setEnabled(true);
    txtData.setEnabled(true);
    txtEndereco.setEnabled(true);
    txtCidade.setEnabled(true);
    
        try {
            conexao.executaSQL("SELECT * FROM funcionario");
            conexao.rs.first();
            txtCodigo.setText(conexao.rs.getString("cod_funcionario"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtFuncao.setText(conexao.rs.getString("funcao"));
            txtComboSexo.setSelectedItem(conexao.rs.getString("sexo"));
            txtCPF.setText(conexao.rs.getString("cpf"));
            txtData.setText(conexao.rs.getString("data_adimissao"));
            txtEndereco.setText(conexao.rs.getString("endereco"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
            txtComboStatus.setSelectedItem(conexao.rs.getString("status"));
            btUltimo.setEnabled(true);
            btProximo.setEnabled(true);
            btPrimeiro.setEnabled(false);
            btAnterior.setEnabled(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao exibir dados!\nERRO: " + ex);
        }
    }//GEN-LAST:event_btPrimeiroActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
    txtNome.setEnabled(true);
    txtFuncao.setEnabled(true);
    txtCPF.setEnabled(true);
    txtData.setEnabled(true);
    txtEndereco.setEnabled(true);
    txtCidade.setEnabled(true);
    
        try {
            conexao.rs.previous();
            txtCodigo.setText(conexao.rs.getString("cod_funcionario"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtFuncao.setText(conexao.rs.getString("funcao"));
            txtComboSexo.setSelectedItem(conexao.rs.getString("sexo"));
            txtCPF.setText(conexao.rs.getString("cpf"));
            txtData.setText(conexao.rs.getString("data_adimissao"));
            txtEndereco.setText(conexao.rs.getString("endereco"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
            txtComboStatus.setSelectedItem(conexao.rs.getString("status"));
            btUltimo.setEnabled(true);
            btProximo.setEnabled(true);
            btPrimeiro.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "este e o primeiro dado da tabela!");
        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
    txtNome.setEnabled(true);
    txtFuncao.setEnabled(true);
    txtCPF.setEnabled(true);
    txtData.setEnabled(true);
    txtEndereco.setEnabled(true);
    txtCidade.setEnabled(true);
    
        try {
            conexao.rs.next();
            txtCodigo.setText(conexao.rs.getString("cod_funcionario"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtFuncao.setText(conexao.rs.getString("funcao"));
            txtComboSexo.setSelectedItem(conexao.rs.getString("sexo"));
            txtCPF.setText(conexao.rs.getString("cpf"));
            txtData.setText(conexao.rs.getString("data_adimissao"));
            txtEndereco.setText(conexao.rs.getString("endereco"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
            txtComboStatus.setSelectedItem(conexao.rs.getString("status"));
            btUltimo.setEnabled(true);
            btProximo.setEnabled(true);
            btPrimeiro.setEnabled(true);
            btAnterior.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "este e o ultimo dado a ser exibido!");
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtComboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComboEstadoActionPerformed

    private void txtTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTabelaMouseClicked
        String cod_funcionario = "" + txtTabela.getValueAt(txtTabela.getSelectedRow(), 0);
        conexao.Conectar();
        
        conexao.executaSQL("SELECT * FROM funcionario WHERE cod_funcionario = '" + cod_funcionario + "'");
        try {
            conexao.rs.first();
            txtCodigo.setText(conexao.rs.getString("cod_funcionario"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtFuncao.setText(conexao.rs.getString("funcao"));
            txtComboSexo.setSelectedItem(conexao.rs.getString("sexo"));
            txtCPF.setText(conexao.rs.getString("cpf"));
            txtData.setText(conexao.rs.getString("data_adimissao"));
            txtEndereco.setText(conexao.rs.getString("endereco"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
            txtComboStatus.setSelectedItem(conexao.rs.getString("status"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Funcionario não cadastrado!\nERRO:" + ex);
        }
    }//GEN-LAST:event_txtTabelaMouseClicked
    public void preencherData(){
        try{
            MaskFormatter form = new MaskFormatter("##/##/####");
            txtData.setFormatterFactory(new DefaultFormatterFactory(form));
            
        } catch (ParseException ex){
            JOptionPane.showMessageDialog(null, "Erro no MaskFormatter!\nERRO:" + ex);
        }
    }
    public void preencherCpf(){
        try{
            MaskFormatter form = new MaskFormatter("###.###.###-##");
            txtCPF.setFormatterFactory(new DefaultFormatterFactory(form));
            
        } catch (ParseException ex){
            JOptionPane.showMessageDialog(null, "Erro no MaskFormatter!\nERRO:" + ex);
        }
    }
    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"Codigo", "Nome", "Função", "sexo", "CPF", "Data  de Adms", "Endereço", "cidade", "Estado", "Status"};
        
        conexao.executaSQL(SQL);
        try {
            conexao.rs.first();
            do{
            dados.add(new Object[]{conexao.rs.getInt("cod_funcionario"), conexao.rs.getString("nome"), conexao.rs.getString("funcao"), conexao.rs.getString("sexo"),conexao.rs.getString("cpf"),conexao.rs.getString("data_adimissao"),conexao.rs.getString("endereco"),conexao.rs.getString("cidade"),conexao.rs.getString("estado"),conexao.rs.getString("status")});
        }while(conexao.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ArrayList!\nERRO: " + ex);
        }
        Tabela modelo = new Tabela(dados, Colunas);
        txtTabela.setModel(modelo);
        txtTabela.getColumnModel().getColumn(0).setPreferredWidth(50);
        txtTabela.getColumnModel().getColumn(0).setResizable(false);
        txtTabela.getColumnModel().getColumn(1).setPreferredWidth(100);
        txtTabela.getColumnModel().getColumn(1).setResizable(false);
        txtTabela.getColumnModel().getColumn(2).setPreferredWidth(70);
        txtTabela.getColumnModel().getColumn(2).setResizable(false);
        txtTabela.getColumnModel().getColumn(3).setPreferredWidth(50);
        txtTabela.getColumnModel().getColumn(3).setResizable(false);
        txtTabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        txtTabela.getColumnModel().getColumn(4).setResizable(false);
        txtTabela.getColumnModel().getColumn(5).setPreferredWidth(95);
        txtTabela.getColumnModel().getColumn(5).setResizable(false);
        txtTabela.getColumnModel().getColumn(6).setPreferredWidth(150);
        txtTabela.getColumnModel().getColumn(6).setResizable(false);
        txtTabela.getColumnModel().getColumn(7).setPreferredWidth(85);
        txtTabela.getColumnModel().getColumn(7).setResizable(false);
        txtTabela.getColumnModel().getColumn(8).setPreferredWidth(85);
        txtTabela.getColumnModel().getColumn(8).setResizable(false);
        txtTabela.getColumnModel().getColumn(9).setPreferredWidth(50);
        txtTabela.getColumnModel().getColumn(9).setResizable(false);
        txtTabela.getTableHeader().setReorderingAllowed(false);
        txtTabela.setAutoResizeMode(txtTabela.AUTO_RESIZE_OFF);
        txtTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
            
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPrimeiro;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btUltimo;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JComboBox<String> txtComboEstado;
    private javax.swing.JComboBox<String> txtComboSexo;
    private javax.swing.JComboBox<String> txtComboStatus;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTable txtTabela;
    // End of variables declaration//GEN-END:variables
}
