/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Utilitarios.Conexao;
import Utilitarios.Tabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Augusto
 */
public class FrmFornecedor extends javax.swing.JFrame {

    Conexao conexao = new Conexao();
    
    public FrmFornecedor() {
        initComponents();
        conexao.Conectar();
        preencherTabela("SELECT * FROM fornecedor ORDER BY cod_fornecedor");
        try{
            MaskFormatter form = new MaskFormatter("(##)####-####");
            txtTelefone.setFormatterFactory(new DefaultFormatterFactory(form));
            
        } catch (ParseException ex){
            JOptionPane.showMessageDialog(null, "Erro no MaskFormatter!\nERRO:" + ex);
        }
        try{
            MaskFormatter form = new MaskFormatter("##.###.###/####-##");
            txtCNPJ.setFormatterFactory(new DefaultFormatterFactory(form));
            
        } catch (ParseException ex){
            JOptionPane.showMessageDialog(null, "Erro no MaskFormatter!\nERRO:" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTabela = new javax.swing.JTable();
        btPrimeiro = new javax.swing.JButton();
        btUltimo = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JFormattedTextField();
        txtComboEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedores");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nome:");

        jLabel4.setText("telefone:");

        jLabel5.setText("Email:");

        txtNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNome.setEnabled(false);

        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEmail.setEnabled(false);

        btAdicionar.setText("Adicionar");
        btAdicionar.setToolTipText("utilize para adicionar um fornecedor");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("utiliza para salvar um fornecedor");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.setToolTipText("utilize para alterar um dado selecionado");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("Utilize através do codigo de fornecedor");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("utilize para cancelar uma operação");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        txtTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txtTabela);

        btPrimeiro.setText("Primeiro");
        btPrimeiro.setToolTipText("mostra o primeiro dado cadastrado");
        btPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrimeiroActionPerformed(evt);
            }
        });

        btUltimo.setText("Ultimo");
        btUltimo.setToolTipText("mostra op ultimo dado cadastrado");
        btUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimoActionPerformed(evt);
            }
        });

        btAnterior.setText("Anterior");
        btAnterior.setToolTipText("mostra o dado anterior");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btProximo.setText("Proximo");
        btProximo.setToolTipText("mostra o proximo dado");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        jLabel6.setText("Empresa:");

        txtEmpresa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEmpresa.setEnabled(false);

        btVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_voltar.png"))); // NOI18N
        btVoltar.setToolTipText("clique para voltar para a janela anterior");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        txtTelefone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefone.setEnabled(false);

        jLabel7.setText("CNPJ:");

        txtCNPJ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCNPJ.setEnabled(false);

        txtComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA\t", "CE", "DF", "ES\t", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        txtComboEstado.setSelectedIndex(12);
        txtComboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComboEstadoActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado:");

        jLabel9.setText("Cidade:");

        txtCidade.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTelefone)
                                    .addGap(245, 245, 245))))
                        .addContainerGap(92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btUltimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btProximo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btSalvar)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir)
                    .addComponent(btCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPrimeiro)
                    .addComponent(btUltimo)
                    .addComponent(btAnterior)
                    .addComponent(btProximo))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de cadastro de fornecedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(616, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        txtNome.setText("");
        txtCodigo.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtEmpresa.setText("");
        txtCNPJ.setText("");
        txtCidade.setText("");
        txtNome.setEnabled(true);
        txtCodigo.setEnabled(false);
        txtTelefone.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEmpresa.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtCidade.setEnabled(true);
        btExcluir.setEnabled(false);

    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            PreparedStatement pst = conexao.conn.prepareStatement("INSERT INTO fornecedor (nome, telefone, email, nome_empresa, cnpj, cidade, estado) VALUES (?, ?, ?, ?, ?, ?, ?)");
            
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtTelefone.getText());
            pst.setString(3, txtEmail.getText());
            pst.setString(4, txtEmpresa.getText());
            pst.setString(5, txtCNPJ.getText());
            pst.setString(6, txtCidade.getText());
            pst.setString(7, txtComboEstado.getSelectedItem().toString());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Fornecedor inserido com sucesso!");
            preencherTabela("SELECT * FROM fornecedor ORDER BY cod_fornecedor");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro na inserção! \n ERRO: " + ex);
        }
        btExcluir.setEnabled(true);
        txtCodigo.setEnabled(true);
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        try{

            PreparedStatement pst = conexao.conn.prepareStatement("UPDATE fornecedor SET nome = ?, telefone = ?, email = ?, nome_empresa = ?, cnpj = ?, cidade = ?, estado = ? WHERE cod_fornecedor = ?");
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtTelefone.getText());
            pst.setString(3, txtEmail.getText());
            pst.setString(4, txtEmpresa.getText());
            pst.setString(5, txtCNPJ.getText());
            pst.setString(6, txtCidade.getText());
            pst.setString(7, txtComboEstado.getSelectedItem().toString());
            pst.setString(8, txtCodigo.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Fornecedor alterado com sucesso!");
            preencherTabela("SELECT * FROM fornecedor ORDER BY cod_fornecedor");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro na alteração! \n ERRO: " + ex);

        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if(txtCodigo.isEnabled() == false){

            txtCodigo.setEnabled(true);
        } else{
            if(txtCodigo.getText().equalsIgnoreCase("") == false){
                try{

                    PreparedStatement pst = conexao.conn.prepareStatement("DELETE FROM fornecedor WHERE cod_fornecedor = ?");
                    pst.setString(1, txtCodigo.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane,"Fornecedor excluido com sucesso!");
                    preencherTabela("SELECT * FROM fornecedor ORDER BY cod_fornecedor");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "erro na exclusão! \n ERRO: " + ex);

                }
                txtNome.setText("");
                txtCodigo.setText("");
                txtTelefone.setText("");
                txtEmail.setText("");
                txtEmpresa.setText("");
                txtCNPJ.setText("");
                txtCidade.setText("");
                txtCodigo.setEnabled(false);

            } else { txtCodigo.setEnabled(false);
                JOptionPane.showMessageDialog(rootPane, "ERRO:\nCampo não pode ser nulo!");
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
    txtNome.setText("");
    txtCodigo.setText("");
    txtTelefone.setText("");
    txtEmail.setText("");
    txtEmpresa.setText("");
    txtCNPJ.setText("");
    txtCidade.setText("");
    txtNome.setEnabled(false);
    txtCodigo.setEnabled(false);
    txtTelefone.setEnabled(false);
    txtEmail.setEnabled(false);
    txtEmpresa.setEnabled(false);
    txtCNPJ.setEnabled(false);
    txtCidade.setEnabled(false);
    btAdicionar.setEnabled(true);

    }//GEN-LAST:event_btCancelarActionPerformed

    private void btPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrimeiroActionPerformed
        txtNome.setEnabled(true);
        txtCodigo.setEnabled(false);
        txtTelefone.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEmpresa.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtCidade.setEnabled(true);
        try {
            conexao.executaSQL("SELECT * FROM fornecedor");
            conexao.rs.first();
            txtCodigo.setText(conexao.rs.getString("cod_fornecedor"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtTelefone.setText(conexao.rs.getString("telefone"));
            txtEmail.setText(conexao.rs.getString("email"));
            txtEmpresa.setText(conexao.rs.getString("nome_empresa"));
            txtCNPJ.setText(conexao.rs.getString("cnpj"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
            btUltimo.setEnabled(true);
            btProximo.setEnabled(true);
            btPrimeiro.setEnabled(false);
            btAnterior.setEnabled(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao exibir dados!\nERRO: " + ex);
        }
    }//GEN-LAST:event_btPrimeiroActionPerformed

    private void btUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimoActionPerformed
        txtNome.setEnabled(true);
        txtCodigo.setEnabled(false);
        txtTelefone.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEmpresa.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtCidade.setEnabled(true);
        try {
            conexao.executaSQL("SELECT * FROM fornecedor");
            conexao.rs.last();
            txtCodigo.setText(conexao.rs.getString("cod_fornecedor"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtTelefone.setText(conexao.rs.getString("telefone"));
            txtEmail.setText(conexao.rs.getString("email"));
            txtEmpresa.setText(conexao.rs.getString("nome_empresa"));
            txtCNPJ.setText(conexao.rs.getString("cnpj"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
            btUltimo.setEnabled(false);
            btProximo.setEnabled(false);
            btPrimeiro.setEnabled(true);
            btAnterior.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao exibir dados!\nERRO: " + ex);
        }

    }//GEN-LAST:event_btUltimoActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        txtNome.setEnabled(true);
        txtCodigo.setEnabled(false);
        txtTelefone.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEmpresa.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtCidade.setEnabled(true);
        try {
            conexao.rs.previous();
            txtCodigo.setText(conexao.rs.getString("cod_fornecedor"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtTelefone.setText(conexao.rs.getString("telefone"));
            txtEmail.setText(conexao.rs.getString("email"));
            txtEmpresa.setText(conexao.rs.getString("nome_empresa"));
            txtCNPJ.setText(conexao.rs.getString("cnpj"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
            btUltimo.setEnabled(true);
            btProximo.setEnabled(true);
            btPrimeiro.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "este e o primeiro dado da tabela!");
        }

    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        txtNome.setEnabled(true);
        txtCodigo.setEnabled(false);
        txtTelefone.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEmpresa.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtCidade.setEnabled(true);
        try {
            conexao.rs.next();
            txtCodigo.setText(conexao.rs.getString("cod_fornecedor"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtTelefone.setText(conexao.rs.getString("telefone"));
            txtEmail.setText(conexao.rs.getString("email"));
            txtEmpresa.setText(conexao.rs.getString("nome_empresa"));
            txtCNPJ.setText(conexao.rs.getString("cnpj"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
            btUltimo.setEnabled(true);
            btProximo.setEnabled(true);
            btPrimeiro.setEnabled(true);
            btAnterior.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "este e o ultimo dado a ser exibido!");
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtComboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComboEstadoActionPerformed

    private void txtTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTabelaMouseClicked
        String cod_fornecedor = "" + txtTabela.getValueAt(txtTabela.getSelectedRow(), 0);
        conexao.Conectar();
        
        conexao.executaSQL("SELECT * FROM fornecedor WHERE cod_fornecedor = '" + cod_fornecedor + "'");
        try {
            conexao.rs.first();
            txtCodigo.setText(conexao.rs.getString("cod_fornecedor"));
            txtNome.setText(conexao.rs.getString("nome"));
            txtTelefone.setText(conexao.rs.getString("telefone"));
            txtEmail.setText(conexao.rs.getString("email"));
            txtEmpresa.setText(conexao.rs.getString("nome_empresa"));
            txtCNPJ.setText(conexao.rs.getString("cnpj"));
            txtCidade.setText(conexao.rs.getString("cidade"));
            txtComboEstado.setSelectedItem(conexao.rs.getString("estado"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Fornecedor não cadastrado!\nERRO:" + ex);
        }
    }//GEN-LAST:event_txtTabelaMouseClicked

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"Codigo", "Nome", "Telefone", "Email", "Empresa", "CNPJ", "Cidade", "Estado"};
        
        conexao.executaSQL(SQL);
        try {
            conexao.rs.first();
            do{
            dados.add(new Object[]{conexao.rs.getInt("cod_fornecedor"), conexao.rs.getString("nome"), conexao.rs.getString("telefone"), conexao.rs.getString("email"), conexao.rs.getString("nome_empresa"),conexao.rs.getString("cnpj"),conexao.rs.getString("cidade"),conexao.rs.getString("estado")});
        }while(conexao.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ArrayList!\nERRO: " + ex);
        }
        Tabela modelo = new Tabela(dados, Colunas);
        txtTabela.setModel(modelo);
        txtTabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        txtTabela.getColumnModel().getColumn(0).setResizable(false);
        txtTabela.getColumnModel().getColumn(1).setPreferredWidth(90);
        txtTabela.getColumnModel().getColumn(1).setResizable(false);
        txtTabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        txtTabela.getColumnModel().getColumn(2).setResizable(false);
        txtTabela.getColumnModel().getColumn(3).setPreferredWidth(125);
        txtTabela.getColumnModel().getColumn(3).setResizable(false);
        txtTabela.getColumnModel().getColumn(4).setPreferredWidth(90);
        txtTabela.getColumnModel().getColumn(4).setResizable(false);
        txtTabela.getColumnModel().getColumn(5).setPreferredWidth(90);
        txtTabela.getColumnModel().getColumn(5).setResizable(false);
        txtTabela.getColumnModel().getColumn(6).setPreferredWidth(90);
        txtTabela.getColumnModel().getColumn(6).setResizable(false);
        txtTabela.getColumnModel().getColumn(7).setPreferredWidth(90);
        txtTabela.getColumnModel().getColumn(7).setResizable(false);
        txtTabela.getTableHeader().setReorderingAllowed(false);
        txtTabela.setAutoResizeMode(txtTabela.AUTO_RESIZE_OFF);
        txtTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
            
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPrimeiro;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btUltimo;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JComboBox<String> txtComboEstado;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTable txtTabela;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
